package de.upteams.tasktracker.user.util;

import de.upteams.tasktracker.user.dto.response.UserResponseDto;
import de.upteams.tasktracker.user.entity.AppUser;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingConstants;
import de.upteams.tasktracker.user.dto.EmployeeDto;
/**
 * Interface for Employee Mapping Service.
 * Implementation of that interface is generated by MapStruct framework.
 */
@Mapper(
        componentModel = MappingConstants.ComponentModel.SPRING
)
public interface AppUserMapper {


    UserResponseDto mapEntityToDto(AppUser entity);

    @Mapping(target = "id", source = "id")
    @Mapping(target = "password", ignore = true)
    @Mapping(target = "avatar", ignore = true)
    @Mapping(target = "roles", ignore = true)
    @Mapping(target = "name", source = "email")
    @Mapping(target = "email", source = "email")
    EmployeeDto mapEntityToEmployeeDto(AppUser entity);
}
