package de.upteams.tasktracker.project.utils;

import de.upteams.tasktracker.collaborator.utils.CollaboratorMapper;
import de.upteams.tasktracker.project.dto.request.ProjectCreateDto;
import de.upteams.tasktracker.project.dto.response.ProjectResponseDto;
import de.upteams.tasktracker.project.entity.Project;
import de.upteams.tasktracker.task.utils.TaskMappingService;
import de.upteams.tasktracker.user.util.AppUserMapper;
import org.mapstruct.*;

/**
 * Interface for Project Mapping Service.
 * Implementation of that interface is generated by MapStruct framework.
 */
@Mapper(
        componentModel = MappingConstants.ComponentModel.SPRING,
        uses = {AppUserMapper.class, TaskMappingService.class, CollaboratorMapper.class},
        nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS,
        collectionMappingStrategy = CollectionMappingStrategy.TARGET_IMMUTABLE

)
public interface ProjectMapper {

    //@Mapping(target = "id", ignore = true)
    //@Mapping(target = "owner", ignore = true)
    @Mapping(
            target = "id",
            expression = "java(entity.getId() != null ? entity.getId().toString() : null)"
    )
    ProjectResponseDto mapEntityToDto(Project entity);

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "owner", ignore = true)
    @Mapping(target = "tasks", ignore = true)
    @Mapping(target = "projectTeam", ignore = true)
    @Mapping(target = "taskStatuses", ignore = true)
    Project mapDtoToEntity(ProjectCreateDto dto);
}
